name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT || 3000 }}" >> .env
          echo "DB_PATH=${{ secrets.DB_PATH || './database/biblioteca.db' }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> .env
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
        shell: bash

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Initialize Database
        run: npm run db

      - name: Start Application in Background
        run: npm start &

      - name: Wait for Server to Start
        run: sleep 15

      - name: Run Login Test
        run: npx playwright test tests/login.spec.ts

      - name: Run Book Reservation Process Test
        run: npx playwright test tests/userDefault/bookReservationProcess.spec.ts

      - name: Run Manage Cart Test
        run: npx playwright test tests/userDefault/manageCart.spec.ts

      - name: Run Search and Filters Test
        run: npx playwright test tests/userDefault/searchAndFilters.spec.ts

      - name: Run Shopping Cart Test
        run: npx playwright test tests/userDefault/shoppingCart.spec.ts

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30